```{r}
pacman::p_load(tidyverse, here, benford.analysis, htmltab, stringi)
```

# Analyzing the integrity of COVID data by country

### COVID: Our World in Data

```{r}
covid <- 
  read_csv("https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv?raw=true") %>% 
  select(iso_code, continent, location, date, 
         new_cases, new_deaths, new_tests, new_vaccinations,
         population, extreme_poverty, human_development_index)
```

### ISO codes

```{r}
codes <-
  read_csv("https://git.io/v564u") %>%
  select(iso_code = `alpha-3`, name)

countries <- 
  covid %>% 
  distinct(iso_code) %>% 
  inner_join(codes, by = "iso_code") %>% 
  pull(iso_code)
```

## Benford analysis

```{r}
filter_data <- 
  function(data, iso_code, my_list){
    iso_code <- enquo(iso_code)
    filtered <- 
      data %>% 
      filter(UQ(iso_code) %in% my_list) %>% 
      pull(new_cases)
}

madiff <- 
  function(filtered) {
    mean <- 
      suspectsTable(filtered) %>% 
      select("absolute.diff") %>% 
      summarise(mean = (mean(absolute.diff))) %>% 
      pull(mean)
  }
```

```{r}
list <- list()

for (i in countries) {
  filtered <- filter_data(covid, iso_code, my_list = i)
  benford <- benford(filtered, 1, sign = "both")
  value <- madiff(benford)
  list[[i]] <- value
}

benford_rank <- 
  as_tibble(list) %>% 
  mutate(col = 1) %>% 
  pivot_longer(-col, names_to = "iso_code", values_to = "benford") %>% 
  select(-col) %>% 
  arrange(iso_code)

benford_rank %>% print(n = Inf)
```

## Democracy Index: The Economist Intelligence Unit

```{r}
democracy <- 
  htmltab("https://en.wikipedia.org/wiki/Democracy_Index", 6) %>% 
  janitor::clean_names() %>% 
  # rename_with(~str_remove(., "x")) %>% 
  select("name" = country, region, "regime" = regime_type, "democracy" = x2020) %>% 
  as_tibble()
```

## Analysis

```{r}
demo <- 
  democracy %>% 
  select(name, regime, democracy) %>% 
  mutate(name = stri_trim_left(name))
```

```{r}
data <- 
  benford_rank %>% 
  inner_join(codes, by = "iso_code") %>% 
  inner_join(demo, by = "name") %>% 
  mutate(democracy = as.numeric(democracy)) %>% 
  select(iso_code, name, benford, democracy, regime)
```

```{r}
data %>% 
  ggplot(aes(x = democracy, y = benford, label = iso_code)) +
  geom_point() +
  geom_text(hjust = 0, vjust = 0)
```

```{r}
summary(lm(benford ~ democracy, data))
```

## References

[\<https://hill.math.gatech.edu/publications/PAPER%20PDFS/TheFirstDigitPhenomenonAmericanScientist1996.pdf>](https://hill.math.gatech.edu/publications/PAPER%20PDFS/TheFirstDigitPhenomenonAmericanScientist1996.pdf){.uri}
